name: Sheetwork

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pip-requirements.txt -r dev-pip-requirements.txt
    - name: Mypy checks
      uses: jpetrucciani/mypy-check@master
      with:
        path: 'core'
    - name: Run Tests and Coverage Report
      run: |
        pytest --cov-report=xml:coverage-reports/coverage.xml --cov-report term-missing  --cov=core tests/
    - name: Upload coverage report to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage-reports/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
