name: Sheetwork CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install --use-feature=2020-resolver -r pip-requirements.txt -r dev-pip-requirements.txt

      - name: Mypy checks
        uses: jpetrucciani/mypy-check@master
        with:
          path: "core"

      - name: Run Tests and Coverage Report
        run: |
          pytest --cov-report=xml:coverage-reports/coverage.xml --cov-report term-missing  --cov=. tests/

      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage-reports/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
